tarball=exceptiongroup-VERSION-py3-none-any.whl
sha1=4114f66482c6e55856d9bd6a4780ce716bd550cd
sha256=5258b9ed329c5bbdd31a309f53cbfb0b155341807f6ff7606a1e801a891b29ad
upstream_url=https://pypi.io/packages/py3/e/exceptiongroup/exceptiongroup-VERSION-py3-none-any.whl
